#!/bin/bash
# InCollege Test Runner
# Automates execution of all test cases and reports results

# Color codes for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# Counters
TOTAL=0
PASSED=0
FAILED=0

# Get the directory where this script is located
SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
PROJECT_ROOT="$( cd "$SCRIPT_DIR/.." && pwd )"
TEST_CASES_DIR="$SCRIPT_DIR/test_cases"
TEST_OUTPUT_DIR="$SCRIPT_DIR/test_cases_output"
REPORTS_DIR="$SCRIPT_DIR/reports"

# Create reports directory if it doesn't exist
mkdir -p "$REPORTS_DIR"

# Generate timestamp for report
TIMESTAMP=$(date '+%Y-%m-%d_%H-%M-%S')
REPORT_FILE="$REPORTS_DIR/test_report_${TIMESTAMP}.md"
SUMMARY_FILE="$REPORTS_DIR/latest_summary.txt"

# Check if InCollege executable exists
if [ ! -f "$PROJECT_ROOT/InCollege" ]; then
    echo -e "${RED}Error: InCollege executable not found in $PROJECT_ROOT${NC}"
    echo "Please compile the program first:"
    echo "  cd $PROJECT_ROOT"
    echo "  cobc -x -free InCollege.cob"
    exit 1
fi

# Check if test directories exist
if [ ! -d "$TEST_CASES_DIR" ]; then
    echo -e "${RED}Error: test_cases directory not found at $TEST_CASES_DIR${NC}"
    exit 1
fi

if [ ! -d "$TEST_OUTPUT_DIR" ]; then
    echo -e "${RED}Error: test_cases_output directory not found at $TEST_OUTPUT_DIR${NC}"
    exit 1
fi

echo "======================================"
echo "   InCollege Test Suite Runner"
echo "======================================"
echo ""
echo "Project Root: $PROJECT_ROOT"
echo "Test Cases: $TEST_CASES_DIR"
echo "Expected Output: $TEST_OUTPUT_DIR"
echo "Reports Directory: $REPORTS_DIR"
echo ""

# Initialize report file
cat > "$REPORT_FILE" << EOF
# InCollege Test Execution Report

**Generated:** $(date '+%Y-%m-%d %H:%M:%S')  
**Project Root:** $PROJECT_ROOT  
**Test Cases Directory:** $TEST_CASES_DIR  

---

## Test Results Summary

EOF

# Get list of all input files
input_files=$(ls "$TEST_CASES_DIR"/Epic1-*-Input.txt 2>/dev/null | sort)

if [ -z "$input_files" ]; then
    echo -e "${RED}Error: No test input files found in $TEST_CASES_DIR${NC}"
    exit 1
fi

# Array to store failed tests
declare -a FAILED_TESTS

# Run each test
for input_file in $input_files; do
    # Extract test name from full path
    test_name=$(basename "$input_file" -Input.txt)
    expected_output="$TEST_OUTPUT_DIR/${test_name}-Output.txt"
    
    # Check if expected output file exists
    if [ ! -f "$expected_output" ]; then
        echo -e "${YELLOW}Warning: Expected output file not found for $test_name${NC}"
        continue
    fi
    
    TOTAL=$((TOTAL + 1))
    
    echo -n "Running $test_name... "
    
    # Clean state - clear accounts.dat contents instead of removing
    if [ -f "$PROJECT_ROOT/accounts.dat" ]; then
        > "$PROJECT_ROOT/accounts.dat"  # Truncate file to zero length
    else
        touch "$PROJECT_ROOT/accounts.dat"  # Create empty file if it doesn't exist
    fi
    
    # Copy input file to project root
    cp "$input_file" "$PROJECT_ROOT/InCollege-Input.txt"
    
    # Run program from project root directory
    cd "$PROJECT_ROOT"
    ./InCollege > /dev/null 2>&1
    cd "$SCRIPT_DIR"
    
    # The actual output is in InCollege-Output.txt generated by the program
    actual_output="$PROJECT_ROOT/InCollege-Output.txt"
    
    # Check if output file was created
    if [ ! -f "$actual_output" ]; then
        echo -e "${RED}❌ FAILED - No output file generated${NC}"
        FAILED=$((FAILED + 1))
        FAILED_TESTS+=("$test_name")
        
        # Add to report
        cat >> "$REPORT_FILE" << EOF
### ❌ $test_name - FAILED

**Status:** FAILED - No output file generated  
**Input File:** \`$test_name-Input.txt\`  
**Expected Output File:** \`$test_name-Output.txt\`  

#### Test Input

\`\`\`
$(cat "$input_file")
\`\`\`

#### Error

The program did not generate InCollege-Output.txt file.

---

EOF
        continue
    fi
    
    # Compare output
    if diff -q "$actual_output" "$expected_output" > /dev/null 2>&1; then
        echo -e "${GREEN}✅ PASSED${NC}"
        PASSED=$((PASSED + 1))
        
        # Add to report
        cat >> "$REPORT_FILE" << EOF
### ✅ $test_name - PASSED

**Status:** PASSED  
**Input File:** \`$test_name-Input.txt\`  
**Expected Output File:** \`$test_name-Output.txt\`  

<details>
<summary>View Test Input</summary>

\`\`\`
$(cat "$input_file")
\`\`\`

</details>

<details>
<summary>View Output</summary>

\`\`\`
$(cat "$actual_output")
\`\`\`

</details>

---

EOF
    else
        echo -e "${RED}❌ FAILED${NC}"
        FAILED=$((FAILED + 1))
        FAILED_TESTS+=("$test_name")
        
        # Show first few lines of difference
        echo "  Differences found:"
        diff "$actual_output" "$expected_output" | head -n 10 | sed 's/^/    /'
        echo ""
        
        # Add detailed failure to report
        cat >> "$REPORT_FILE" << EOF
### ❌ $test_name - FAILED

**Status:** FAILED  
**Input File:** \`$test_name-Input.txt\`  
**Expected Output File:** \`$test_name-Output.txt\`  

#### Test Input

\`\`\`
$(cat "$input_file")
\`\`\`

#### Expected Output

\`\`\`
$(cat "$expected_output")
\`\`\`

#### Actual Output

\`\`\`
$(cat "$actual_output")
\`\`\`

#### Differences

\`\`\`diff
$(diff -u "$expected_output" "$actual_output")
\`\`\`

---

EOF
    fi
    
    # Return to script directory
    cd "$SCRIPT_DIR"
done

# Clean up
rm -f "$PROJECT_ROOT/InCollege-Input.txt"
rm -f "$PROJECT_ROOT/InCollege-Output.txt"

# Add summary to beginning of report
summary_content="| Metric | Count |
|--------|-------|
| Total Tests | $TOTAL |
| Passed | $PASSED |
| Failed | $FAILED |
| Pass Rate | $(awk "BEGIN {printf \"%.1f%%\", ($PASSED/$TOTAL)*100}") |"

# Insert summary after the summary header
sed -i "/## Test Results Summary/a\\
\\
$summary_content\\
" "$REPORT_FILE"

# Add failed tests list if any
if [ $FAILED -gt 0 ]; then
    cat >> "$REPORT_FILE" << EOF

## Failed Tests

The following tests failed:

EOF
    for test in "${FAILED_TESTS[@]}"; do
        echo "- [$test](#$(echo $test | tr '[:upper:]' '[:lower:]' | tr ' ' '-')-failed)" >> "$REPORT_FILE"
    done
    
    cat >> "$REPORT_FILE" << EOF

---

## Detailed Test Results

EOF
else
    cat >> "$REPORT_FILE" << EOF

🎉 **All tests passed!**

---

## Detailed Test Results

EOF
fi

# Create summary file
cat > "$SUMMARY_FILE" << EOF
InCollege Test Execution Summary
Generated: $(date '+%Y-%m-%d %H:%M:%S')
========================================

Total Tests:  $TOTAL
Passed:       $PASSED
Failed:       $FAILED
Pass Rate:    $(awk "BEGIN {printf \"%.1f%%\", ($PASSED/$TOTAL)*100}")

EOF

if [ $FAILED -gt 0 ]; then
    cat >> "$SUMMARY_FILE" << EOF
Failed Tests:
EOF
    for test in "${FAILED_TESTS[@]}"; do
        echo "  - $test" >> "$SUMMARY_FILE"
    done
fi

cat >> "$SUMMARY_FILE" << EOF

Full Report: $REPORT_FILE
EOF

# Console summary
echo ""
echo "======================================"
echo "           Test Summary"
echo "======================================"
echo "Total Tests:  $TOTAL"
echo -e "Passed:       ${GREEN}$PASSED${NC}"
echo -e "Failed:       ${RED}$FAILED${NC}"
echo "Pass Rate:    $(awk "BEGIN {printf \"%.1f%%\", ($PASSED/$TOTAL)*100}")"
echo ""
echo -e "${BLUE}📊 Detailed report saved to:${NC}"
echo "   $REPORT_FILE"
echo ""
echo -e "${BLUE}📄 Summary saved to:${NC}"
echo "   $SUMMARY_FILE"

if [ $FAILED -eq 0 ]; then
    echo ""
    echo -e "${GREEN}🎉 All tests passed!${NC}"
    exit 0
else
    echo ""
    echo -e "${RED}⚠️  Some tests failed. Please review the report.${NC}"
    echo ""
    echo "Failed tests:"
    for test in "${FAILED_TESTS[@]}"; do
        echo -e "  ${RED}✗${NC} $test"
    done
    exit 1
fi
